name = "ABCDOptics"
uuid = "210ef64c-ad11-4f70-9aef-6554e157303b"
authors = ["Brian Sinquin <paradisepx@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
